# Generated by Django 3.0.7 on 2020-06-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
