# Generated by Django 3.0.7 on 2020-07-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_courier_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
