# Generated by Django 3.0.7 on 2020-07-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20200705_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_phone_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
