# Generated by Django 3.0.7 on 2020-07-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20200708_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Courier'),
        ),
    ]
