# Generated by Django 3.0.7 on 2020-07-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20200709_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='wish',
            new_name='comment',
        ),
    ]
